#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2002, David Ryan ( Oobles@hotmail.com )
#  ------------------------------------------------------------------------

COMMON_INC = $(TOPDIR)/common/include
COMMON_LIB = $(TOPDIR)/common/lwip

IOP_INCS += -I$(COMMON_INC) -I$(COMMON_INC)/ipv4

IOP_LDFLAGS += -L$(COMMON_LIB)
